name: Deploy to Fly.io

on:
  push:
    branches:
      - main  # Adjust to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install flyctl
        run: |
          curl -L https://fly.io/install.sh | sh

      - name: Log in to Fly.io
        run: flyctl login --token ${{ secrets.FLY_API_TOKEN }}
        
      - name: Deploy to Fly.io
        run: flyctl deploy

      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
